{% set name = "napari-arboretum" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: eec5979f32881cdd7ec8205b8d895918a5e64ddb020a9eb2745381785d6b4df2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - matplotlib-base
    - napari >=0.4.0
    - napari-matplotlib >=0.2.1
    - numpy >=1.17.3
    - pandas
    - pooch >=1
    - python >=3.8
    - qtpy
    - scikit-image
    - vispy

test:
  imports:
    - napari_arboretum
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/napari-arboretum
  summary: Track graph and lineage tree visualization with napari
  license: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/lowe-lab-ucl/arboretum

extra:
  recipe-maintainers:
    - quantumjot
    - goanpeca
    - jaimergp
