{% set name = "napari-arboretum" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-arboretum-{{ version }}.tar.gz
  sha256: e9726a255dc78c9eb4e9eb61b21a20fd713e422278c4f1ef912d73e654ae3e36

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - matplotlib
    - napari >=0.4.0
    - napari-matplotlib >=0.2.1
    - numpy >=1.17.3
    - pandas
    - pooch >=1
    - vispy

test:
  imports:
    - napari_arboretum
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/quantumjot/arboretum
  summary: Track graph and lineage tree visualization with napari
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - quantumjot
    - conda-forge/napari
