{% set name = "napari-arboretum" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-arboretum-{{ version }}.tar.gz
  sha256: 9b1837bb02727edd045b7a341af29bd466aef3ae01bbc81141c71117cd5b6078
  patches:
    - import.patch  # Use `qtpy` instead of `pyqt5`

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - matplotlib-base
    - napari >=0.4.0
    - napari-matplotlib >=0.2.1
    - numpy >=1.17.3
    - qtpy
    - pandas
    - pooch >=1
    - python >=3.8
    - scikit-image
    - vispy

test:
  imports:
    - napari_arboretum
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/quantumjot/arboretum
  summary: Track graph and lineage tree visualization with napari
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - quantumjot
    - goanpeca
    - jaimergp
